Add rule to check for space after colon
orsinium-labs/flake8-todos pull request #1
Opened 2022-11-08 13:00 UTC by CalumY

This PR adds a check to make sure that TODOs have a space after the colon. 

For example: 

**Passing**

`# TODO(author): i have a space'`

**Failing**

`# TODO(author):i need a space'`

2022-11-08 14:13 UTC, orsinium requested changes
Great work! A few small nitpicks, and I'll merge and release it. Thank you for using the project and contributing back ❤️

2022-11-08 14:13 UTC, orsinium commented on README.md
> ++ **T007**: missed space in TODO.
Make this text the same as in the actual rule, please

```suggestion
+ **T007**: missed space after colon in TODO.
```

2022-11-08 14:13 UTC, orsinium commented on flake8_todos/_rules.py
> +        if ' ' not in token.string:
Make a test case for this branch too, please.

2022-11-08 15:09 UTC, calumy commented on flake8_todos/_rules.py
> +        if ' ' not in token.string:
Test case added in: f2bcb53818986826f2f87b5a19f797347c620c4b

2022-11-10 09:17 UTC, orsinium commented
Thank you!

2022-11-10 09:17 UTC, merged

2022-11-17 19:14 UTC, AIGeneratedUsername commented
@CalumY You made a breaking change for people who ignore the `T002` rule (author).

Now for all my comments like
```
# TODO: bla bla bla
```
I have a `T007: missed space after colon in TODO` error which is incorrect.

I am no disusing here whether people must specify `author` or not. I am telling that your check says wrong things.

2022-11-18 09:59 UTC, orsinium commented
@AIGeneratedUsername Thank you for reaching out, good catch :) Do you want to contribute a correct implementation?

2022-11-18 17:23 UTC, AIGeneratedUsername commented
> @AIGeneratedUsername Thank you for reaching out, good catch :) Do you want to contribute a correct implementation?

I can, but I am sorry, no time estimation because of regular blackouts due to russian bombing my home with rockets. I will start when I will have time, but if someone will contribute a fix faster, I will be totally happy with that.

2022-11-19 07:17 UTC, orsinium commented
Oh my! Good luck, man. That's all an awful story. У меня друг в последний момент успел из Киева уехать. Он многих друзей потерял, работу... Скорее бы это всё закончилось...

I'll have a look into the fix in a few days, that shouldn't be that hard.

2022-11-19 16:01 UTC, CalumY commented
@orsinium and @AIGeneratedUsername, hopefully #3 solves the problem.